//
//  SortOrder.h
//  Beezle
//
//  Created by KM Lagerstrom on 02/02/2012.
//  Copyright (c) 2012 __MyCompanyName__. All rights reserved.
//

typedef enum
{
	Z_ORDER_BACKGROUND,
	Z_ORDER_BEEATER_BODY,
	Z_ORDER_BEEATER_HEAD,
	Z_ORDER_LEAF,
	Z_ORDER_RAMP,
	Z_ORDER_POLLEN,
	Z_ORDER_MUSHROOM,
	Z_ORDER_WOOD,
	Z_ORDER_NUT,
	Z_ORDER_EGG,
	Z_ORDER_HANGNEST_LIAN,
	Z_ORDER_HANGNEST,
	Z_ORDER_AIM_POLLEN,
	Z_ORDER_BEE_QUEUE,
	Z_ORDER_BEE,
	Z_ORDER_SLINGER,
} SortOrder;
